#!/usr/bin/env bash
# Fixes Nginx so that it listens on port 80 by changing the port in the default configuration file.

sudo sed -i 's/listen 8080;/listen 80;/g' /etc/nginx/sites-enabled/default

sudo service nginx restart
